### ISSUE TITLE
Find a way to use DOA classes inside interfaces in Catalyst.Abstractions

### ISSUE THREAD

**Issue by Xela101** [catalyst-network/Catalyst.Framework#1023]
Currently some interfaces in Catalyst.Abstractions are Generic so they can be used by types that are not referenced in Catalyst.Abstractions such as DOA, DOA lives in Catalyst.Code.Lib and should be referenced directly in Catalyst.Abstractions because #1 it would be a bad design and #2 creates a circular reference anyway.

Other choices:
#1 Create a new Project with the DOA classes similar to Protobuffs and reference them from Abstractions(My Pick).
#2 Move DOA classes into Catalyst.Abstractions.
#3 Keep Generic Interface.

Any other options post below.

**Comment by Xela101** [comment]
> * Have an interface that can be implemented by all those DOA and protos, and used throughout the solution regardless of what the underlying object is (eg ITransaction), but really, the proto object might influence almost entirely what this interface looks like, so I am not sure it has value, so the other way is:
> * Keep the proto around, with their partial methods, and reference them in Abstractions (my favourite 😂 I'm getting old, don't like change etc 👴 😂 )

Repository's cannot use interfaces.

**Comment by monsieurleberre** [comment]
OK let's think about this one again, what is the issue with what I believe is the current behaviour:
1) Abstractions references Protocol
2) Protocol has some convenience methods when needed/possible
3) When not possible in Protocol, protocol object can be augmented with extension methods in the correct project (ex: to build an address from a public key, you need some hashing, so maybe it can be done in Core)
4) When some protocol object needs to be stored in a repo, it gets converted just before the call to save it, and when it needs to be read back, the DAO gets converted back into the protocol object

Sorry if it is an obvious one to you, for me it looks acceptable until we really need to do better (and maybe we already do)
I think that the change from protocol to DAO too early, or everywhere in the code, will end up bloating the DAO class the way the Proto ones apparently already are, and defeat the DAO purpose. Really happy to discuss, sorry for being such a pain 😂

**Comment by Xela101** [comment]
DAOs should only be used for data access and converted to their protobuf types for usage. Got a little confused, makes sense.
