### ISSUE TITLE
Decide what to do with the DeltaHashProvider when we cannot find a hash which is too far in the past

### ISSUE THREAD

**Issue by monsieurleberre** [catalyst-network/Catalyst.Framework#615]
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Complete the task associated to this 'TODO' comment.](https://app.codacy.com/app/catalyst-network/Catalyst.Node/pullRequest?prid=3802947)

_Originally posted by @nshCore in https://github.com/catalyst-network/Catalyst.Node/pull/612_

**Comment by nshCore** [comment]
You should always find a delta otherwise we have problems beyond the scope of this ticket!
