### ISSUE TITLE
As a developer I want to get better tests around the new proto validators

### ISSUE THREAD

**Issue by monsieurleberre** [catalyst-network/Catalyst.Framework#996]
‒ Why hasn't it been done during/before those developments?
‒ They were added in a rush to get through with the refactor...
‒ This is not a valid excuse, untested code shouldn't get merged
‒ Well, people were waiting on that code to progress with theirs.
‒ Whatever you say to make yourself feel better dude, that is not acceptable
‒ Sorry

**Comment by nshCore** [comment]
tests added to this, not sure about the context of your conversation?
